#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a yourls
if [[ ! $? -eq 0 ]]; then
exit 1
fi

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'yourls' as database name and user
db_user=yourls

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting yourls mysqlpwd -v $db_pwd


# Copy files to the right place
final_path=/var/www/yourls
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path


sudo cp $final_path/user/config-sample.php $final_path/user/config.php

# Set permissions
sudo chown -R www-data: $final_path