#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
admin_user=$3
upload_password=$4

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a yourls
if [[ ! $? -eq 0 ]]; then
exit 1
fi

# Check that admin user is an existing account
sudo yunohost user list --json | grep -q "\"username\": \"$admin_user\""
if [[ ! $? -eq 0 ]]; then
    echo "Error : the chosen admin user does not exist"
    exit 1
fi

# Generate random password
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{24\}\).*/\1/p')

# Use 'yourls' as database name and user
db_user=yourls

# Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting yourls mysqlpwd -v $db_pwd


# Copy files to the right place
final_path=/var/www/yourls
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Change variable in yourls configuration
sudo cp ../conf/config.php $final_path/user/config.php
sudo sed -i "s/yunouser/$db_user/g" $final_path/user/config.php
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/user/config.php
sudo sed -i "s/yunobase/$db_user/g" $final_path/user/config.php
sudo sed -i "s/yunodomain/$domain/g" $final_path/user/config.php
sudo sed -i "s/yourlsuser/$admin_user/g" $final_path/user/config.php
sudo sed -i "s/yourlspass/$upload_password/g" $final_path/user/config.php
sudo sed -i "s/_yourlspath$path/g" $final_path/user/config.php


# Set permissions
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
nginxconf=/etc/nginx/conf.d/$domain.d/yourls.conf
sudo cp ../conf/nginx.conf $nginxconf
sudo chown root: $nginxconf
sudo chmod 600 $nginxconf

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf