#!/bin/bash

db_user=yourls
db_name=yourls
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting yourls domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"

sudo rm -rf /var/www/yourls
sudo rm -f /etc/nginx/conf.d/$domain.d/yourls.conf