#!/bin/bash


# Retrieve arguments
domain=$(sudo yunohost app setting yourls domain)
path=$(sudo yunohost app setting yourls path)
db_user=yourls
db_pwd=$(sudo yunohost app setting yourls mysqlpwd)
admin_user=$(sudo yunohost app setting yourls admin)


# Copy files to the right place
final_path=/var/www/yourls
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

sudo cp ../conf/index.php $final_path/
sudo cp -r ../conf/yunohost_auth $final_path/user/plugins


# Change variable in yourls configuration
sudo cp ../conf/config.php $final_path/user/config.php
sudo sed -i "s/yunouser/$db_user/g" $final_path/user/config.php
sudo sed -i "s/yunopass/$db_pwd/g" $final_path/user/config.php
sudo sed -i "s/yunobase/$db_user/g" $final_path/user/config.php
sudo sed -i "s/yunodomain/$domain/g" $final_path/user/config.php
sudo sed -i "s/yourlsuser/$admin_user/g" $final_path/user/config.php
sudo sed -i "s@_yourlspath@$path@g" $final_path/user/config.php

# Set permissions
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@LOCATIONTOCHANGE@$path@g" ../conf/nginx.conf*
sed -i "s@PATHTOCHANGE@${path%/}@g" ../conf/nginx.conf*
sed -i "s@DOMAINTOCHANGE@$domain@g" ../conf/nginx.conf*
sed -i "s@ALIASTOCHANGE@$final_path@g" ../conf/nginx.conf*
nginxconf=/etc/nginx/conf.d/$domain.d/yourls.conf
sudo cp ../conf/nginx.conf $nginxconf
sudo chown root: $nginxconf
sudo chmod 600 $nginxconf

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app setting yourls unprotected_uris -v "/"
sudo yunohost app ssowatconf

